/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package connect4.common.model

import connect4.test.Fast
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

@Fast
internal class StateTest {
    private lateinit var state: State

    @BeforeEach
    fun init() {
        this.state = State()
    }

    @Test
    fun `given a new state, when no calls done, expect value to be START`() {
        assertEquals(StateValue.START, this.state.value)
    }

    @Test
    fun `given a new state, when next() called, expect value to be PLAY`() {
        this.state.next()
        assertEquals(StateValue.PLAY, this.state.value)
    }

    @Test
    fun `given a PLAY state, when next() called, expect value to be RESUME`() {
        this.goToLastStateValue()
        assertEquals(StateValue.RESUME, this.state.value)
    }

    @Test
    fun `given a RESUME state, when next() called, expect to fail`() {
        this.goToLastStateValue()
        assertThrows(ArrayIndexOutOfBoundsException::class.java) { this.state.next() }
    }

    @Test
    fun `given a RESUME state, when reset() called, expect value to be START`() {
        this.goToLastStateValue()
        this.state.reset()
        assertEquals(StateValue.START, this.state.value)
    }

    private fun goToLastStateValue() {
        this.state.next()
        this.state.next()
    }
}
